name: Generate Snake
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"  # Este cronjob roda a cada 24 horas

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      # Gera a animação de cobrinha
      - uses: Platane/snk@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Commit e Push da animação de cobrinha na branch main
      - name: Commit and Push Snake Animation to main
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add dist/github-contribution-grid-snake.svg
          git commit -m "Add contribution grid snake animation"
          git push origin main
